# Stores the default config values to be used on start up if no other config values are provided.
DEFAULT_CONFIG_VALUES = {
    "CONFIG_CYLINDER_DIAMETER": 30.0, 
    "CONFIG_CYLINDER_LENGTH": 160.0, # cylinder length
    "CONFIG_CHANNELS_DIAMETER": 2.7, # channels diameter
    "CONFIG_NEEDLE_LENGTH": 294.0,
    "CONFIG_TANDEM_TIP_HEIGHT": 129.0, 
    "CONFIG_TANDEM_CHANNEL_DIAMETER": 3.8, 
    "CONFIG_TANDEM_STOPPER_DIAMETER": 5.0, 
    "CONFIG_TANDEM_TIP_ANGLE": 0,
    "CONFIG_TANDEM_BEND_RADIUS": 35.0,
    "CONFIG_CHANNELS_THREADING_DEPTH": 3.5,
    "CONFIG_CHANNELS_THREADING_DIAMETER": 3.5,
    "CONFIG_TANDEM_ROTATION": 0.0,
    "CONFIG_TANDEM_THREADING_DEPTH": 0.0,
    "CONFIG_TANDEM_THREADING_DIAMETER": 0.0
}